name: AWS Assume Role (OIDC)

env:
  terraform_root_dir: "terraform-demo"

on: push

permissions:
  id-token: write
  contents: read

jobs:
  assume-role:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS assume role with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::992382678496:role/GitHubActionsAdminRole

      - name: Get caller identity
        run: |
          aws sts get-caller-identity

      - id: repo-basename
        run: |
          echo "value=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
        shell: bash

      - name: print repo name
        run: |
          echo ${{ steps.repo-basename.outputs.value }}

      - name: Generate backend.tf
        run: |
          bucket_name="terraform-state-992382678496"
          dynamodb_table="terraform-lock-992382678496"
          region="us-east-1"
          workspace=${{ steps.repo-basename.outputs.value }}
          environment="dev"
          backend_config=$(cat <<EOF
          terraform {
            backend "s3" {
              bucket         = "$bucket_name"
              key            = "$workspace/$environment.terraform.tfstate"
              region         = "$region"
              encrypt        = true
              dynamodb_table = "$dynamodb_table"
            }
          }
          EOF
          )
          echo "$backend_config" > "./${{ env.terraform_root_dir }}/backend-new.tf"

      - name: list dir
        run: |
          ls -la terraform-demo
          cat ./terraform-demo/backend-new.tf