name: Terraform Plan

on: push

jobs:
  terraform-plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform Plan
        run: |
          cd terraform-demo
          terraform init
          terraform plan